version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      #POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      #POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data: